site_name: "Portefeuille de Willot Desse Estheban"

theme:
  name: material
  palette:
    scheme: slate  
    primary: blue
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  logo: images/profil.webp  

nav:
  - Accueil: index.md
  - Profil: 
      - Profil : 01_Profil/index.md
      - Mise en place du portfolio: 01_Profil/mise-en-place-doc.md
  - SLAM: 02_SLAM/index.md
  - Cybersécurité: 03_CyberSécurité/index.md
  - Veille technologique: 04_Veille/index.md
  - Synthèse: 05_Synthèse/index.md
  - Contact: 06_contact/index.md

plugins:
  - search
  - mkdocs-nav-weight

markdown_extensions:
  - toc:
      permalink: true
  - tables
  - admonition
  - attr_list