site_name: "Portefeuille de Willot Desse Estheban"

theme:
  name: material

nav:
  - Accueil: index.md
  - Mon Profil:
      - Présentation: 01_Profil/index.md
  - Spécialité SLAM:
      - Présentation: 02_SLAM/index.md
  - CyberSécurité:
      - Présentation: 03_CyberSécurité/index.md
  - Veille Technologique:
      - Présentation: 04_Veille/index.md
  - Synthèse:
      - Tableau de synthèse: 05_Synthèse/Tableau-de-synthèse-des-réalisations-professionnelles.md
  - Contact:
      - Me contacter: 06_contact/index.md

plugins:
  - search
  - mkdocs-nav-weight

markdown_extensions:
  - toc:
      permalink: true
  - tables
  - admonition
