site_name: "Portefeuille de Willot Desse Estheban"

theme:
  name: material
  palette:
    scheme: slate  
    primary: blue
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  logo: images/profil.webp  

nav:
  - Accueil: index.md
  - Mon Profil:
    - Présentation: 01_Profil/index.md
    - Mise en place documentaire: 01_Profil/mise-en-place-doc.md
  - SLAM: 02_SLAM/index.md
  - CyberSécurité: 03_CyberSecurite/index.md
  - Veille technologique: 04_Veille/index.md
  - Synthèse: 05_Synthese/Tableau-de-synthèse-des-réalisations-professionnelles.md
  - Contact: 06_Contact/index.md

plugins:
  - search
  - mkdocs-nav-weight

markdown_extensions:
  - toc:
      permalink: true
  - tables
  - admonition
  - attr_list