site_name: "Portefeuille de Willot Desse Estheban"

theme:
  name: material
  palette:
    - scheme: default
      primary: blue
      accent: indigo
    - scheme: slate
      primary: blue
      accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  logo: images/profil.webp  

nav:
  - Accueil: index.md
  - Profil: 01_Profil/index.md
  - SLAM: 02_SLAM/index.md
  - Cybersecurite: 03_Cybersecurite/index.md
  - Veille technologique: 04_Veille/index.md
  - Mise en place du portfolio: 05_Profil/MDPD.md
  - Synthese: 06_Synthese/Tableau_Synthese.md
  - Contact: 07_Contact/index.md

plugins:
  - search
  - mkdocs-nav-weight

markdown_extensions:
  - toc:
      permalink: true
  - tables
  - admonition
  - attr_list
