site_name: Mon Portfolio

theme:
  name: readthedocs

nav:
  - Accueil: index.md
  - Compétences:
      - Réseaux: reseaux.md
      - Développement: dev.md
      - Cybersécurité: cyber.md
  - Projets:
      - Portfolio: portfolio.md
      - Stage: stage.md
  - À propos: apropos.md


plugins:
  - search  # Plugin de recherche intégré
  - mkdocs-nav-weight  # Plugin pour une meilleure gestion des pages