site_name: "Portefeuille de Willot Desse Estheban"

theme:
  name: readthedocs
  features:
    - navigation.tabs
  palette:
    scheme: slate  
    primary: blue
    accent: indigo
  font:
    text: Roboto
    code: Roboto Mono
  logo: images/profil.webp  

nav:
  - Accueil: index.md
  - Profil: 01_Profil/index.md
  - Mise en place du portfolio: 01_Profil/mise-en-place-doc.md
  - SLAM: 02_SLAM/index.md
  - Cybersecurite: 03_Cybersecurite/index.md
  - Veille technologique: 04_Veille/index.md
  - Synthese: 05_Synthese/Tableau_Synthese.md
  - Contact: 06_Contact/index.md

plugins:
  - search
  - mkdocs-nav-weight

markdown_extensions:
  - toc:
      permalink: true
  - tables
  - admonition
  - attr_list
