site_name: Mon Portfolio

theme:
  name: readthedocs

nav:
  - Accueil: index.md

plugins:
  - search  # Plugin de recherche intégré
  - mkdocs-nav-weight  # Plugin pour une meilleure gestion des pages